# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  schedule:
    # runs at UTC 18:00 every day
    # i.e., runs at 2:00 every day
    - cron: '0 18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Get Data
        run: |
          node get_data.js
          git init
          git config user.name  "CI"
          git config user.email "nodejs-ci@github.com"
          git remote add secure-origin https://${{ secrets.NPM_CI }}@github.com/liao2000/${{ github.event.repository.name }}
          git add .
          git commit -m "get the latest data from CDC"
          git push --force
