# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  schedule:
    # runs at 19:00 UTC+8 every day
    - cron: '0 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Get Data
        run: |
          cd bot
          npm install
          npm run vaccine
          cd ../
          git init
          git config user.name  "CI"
          git config user.email "nodejs-ci@github.com"
          git remote add secure-origin https://${{ secrets.NPM_CI }}@github.com/liao2000/${{ github.event.repository.name }}
          git add .
          git commit -m "Get vaccine data from CDC"
          git push --force
